name: Daily Build

on:
  schedule:
    - cron: 45 17 * * *
  push:
    branches:
      - main
    paths:
      - '.github/start/daily'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install coreutils
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

    - name: Set env variables
      run: |
        echo "RELEASE_NAME=Released on $(date +%Y%m%d)" >> $GITHUB_ENV
        echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Download GeoIPv6
      env:
        LINK: ${{ secrets.Geo_AS_IP_CN_IPV6_LINK }}
      run: |
          curl -LR "${LINK}" -o v6.txt

    - name: Download Misaka Chnroute
      run: |
          curl -LR -o v4.txt "https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt"

    - name: Merge List
      run: |
          cat v4.txt v6.txt > chnroutes.txt

    - name: Push to release branch
      run: |
        mkdir publish
        cp -af chnroutes.txt publish/chnroutes.txt
        cd publish
        git init
        git config --local user.name "${{ github.actor }}"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -b release
        git add .
        git commit -m "${{ env.RELEASE_NAME }}"
        git remote add origin "https://${{ github.actor }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin release
